const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const moment = require('moment');

class PDFGenerator {
  constructor() {
    this.defaultOptions = {
      margin: 50,
      size: 'A4',
      layout: 'portrait'
    };
  }

  async generateGradeReport(reportData, options = {}) {
    const doc = new PDFDocument({ ...this.defaultOptions, ...options });
    const buffers = [];

    return new Promise((resolve, reject) => {
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });
      doc.on('error', reject);

      this.generateGradeReportContent(doc, reportData);
      doc.end();
    });
  }

  generateGradeReportContent(doc, reportData) {
    const { student, semester, grades, generated_at, average_grade, total_grades } = reportData;

    doc.fontSize(20).text('Academic Grade Report', { align: 'center' });
    doc.moveDown();

    doc.fontSize(14).text(`Student Name: ${student.nombre} ${student.apellido}`);
    doc.text(`Grade Level: ${student.grado}`);
    doc.text(`Email: ${student.email}`);
    doc.moveDown();

    doc.text(`Academic Period: ${semester.name} ${semester.year}`);
    doc.text(`Period Dates: ${moment(semester.start_date).format('MMM DD, YYYY')} - ${moment(semester.end_date).format('MMM DD, YYYY')}`);
    doc.text(`Report Generated: ${moment(generated_at).format('MMMM DD, YYYY [at] h:mm A')}`);
    doc.moveDown();

    doc.fontSize(16).text('Academic Performance', { underline: true });
    doc.moveDown(0.5);

    if (grades && grades.length > 0) {
      this.drawGradesTable(doc, grades);

      doc.moveDown();
      doc.fontSize(14).text('Summary Statistics', { underline: true });
      doc.moveDown(0.5);

      doc.fontSize(12);
      doc.text(`Overall Average: ${average_grade}`);
      doc.text(`Total Subjects: ${total_grades}`);

      const highestGrade = Math.max(...grades.map(g => g.grade));
      const lowestGrade = Math.min(...grades.map(g => g.grade));
      doc.text(`Highest Grade: ${highestGrade}`);
      doc.text(`Lowest Grade: ${lowestGrade}`);
    } else {
      doc.fontSize(12).text('No grades available for this academic period.');
    }

    doc.moveDown();
    doc.fontSize(10).text('This is an official academic report generated by the Skolaris system.', { align: 'center' });
    doc.text(`Generated on ${moment().format('MMMM DD, YYYY [at] h:mm A')}`, { align: 'center' });
  }

  drawGradesTable(doc, grades) {
    const tableTop = doc.y;
    const itemFontSize = 10;
    const lineHeight = 20;
    const tableWidth = doc.page.width - (doc.page.margins.left + doc.page.margins.right);

    const columnWidths = {
      subject: tableWidth * 0.35,
      grade: tableWidth * 0.15,
      scale: tableWidth * 0.15,
      teacher: tableWidth * 0.35
    };

    doc.fontSize(itemFontSize);

    doc.text('Subject', doc.page.margins.left, tableTop);
    doc.text('Grade', doc.page.margins.left + columnWidths.subject, tableTop);
    doc.text('Scale', doc.page.margins.left + columnWidths.subject + columnWidths.grade, tableTop);
    doc.text('Teacher', doc.page.margins.left + columnWidths.subject + columnWidths.grade + columnWidths.scale, tableTop);

    doc.moveTo(doc.page.margins.left, tableTop + 15)
      .lineTo(doc.page.margins.left + tableWidth, tableTop + 15)
      .lineWidth(1)
      .stroke();

    let currentY = tableTop + 25;
    grades.forEach((grade, index) => {
      if (currentY > doc.page.height - doc.page.margins.bottom - 50) {
        doc.addPage();
        currentY = doc.page.margins.top;
      }

      const yPosition = currentY + (index * lineHeight);

      doc.text(grade.subject || 'N/A', doc.page.margins.left, yPosition, { width: columnWidths.subject });
      doc.text(grade.grade.toString(), doc.page.margins.left + columnWidths.subject, yPosition, { width: columnWidths.grade });
      doc.text(grade.scale || '0-100', doc.page.margins.left + columnWidths.subject + columnWidths.grade, yPosition, { width: columnWidths.scale });
      doc.text(grade.teacher || 'N/A', doc.page.margins.left + columnWidths.subject + columnWidths.grade + columnWidths.scale, yPosition, { width: columnWidths.teacher });

      if (grade.comments) {
        currentY += 10;
        doc.fontSize(8);
        doc.text(`Comments: ${grade.comments}`, doc.page.margins.left + 20, yPosition + 12, { width: tableWidth - 20 });
        doc.fontSize(itemFontSize);
        currentY += 10;
      }
    });

    doc.y = currentY + (grades.length * lineHeight) + 20;
  }

  async generateAttendanceReport(reportData, options = {}) {
    const doc = new PDFDocument({ ...this.defaultOptions, ...options });
    const buffers = [];

    return new Promise((resolve, reject) => {
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });
      doc.on('error', reject);

      this.generateAttendanceReportContent(doc, reportData);
      doc.end();
    });
  }

  generateAttendanceReportContent(doc, reportData) {
    const { student, semester, attendance_summary, generated_at } = reportData;

    doc.fontSize(20).text('Attendance Report', { align: 'center' });
    doc.moveDown();

    doc.fontSize(14).text(`Student Name: ${student.nombre} ${student.apellido}`);
    doc.text(`Grade Level: ${student.grado}`);
    doc.text(`Email: ${student.email}`);
    doc.moveDown();

    doc.text(`Academic Period: ${semester.name} ${semester.year}`);
    doc.text(`Report Generated: ${moment(generated_at).format('MMMM DD, YYYY [at] h:mm A')}`);
    doc.moveDown();

    doc.fontSize(16).text('Attendance Summary', { underline: true });
    doc.moveDown(0.5);

    if (attendance_summary) {
      doc.fontSize(12);
      doc.text(`Total School Days: ${attendance_summary.total_days}`);
      doc.text(`Days Present: ${attendance_summary.days_present}`);
      doc.text(`Days Absent: ${attendance_summary.days_absent}`);
      doc.text(`Days Tardy: ${attendance_summary.days_tardy}`);
      doc.text(`Attendance Rate: ${attendance_summary.attendance_rate}%`);
    } else {
      doc.fontSize(12).text('No attendance data available for this period.');
    }

    doc.moveDown();
    doc.fontSize(10).text('This is an official attendance report generated by the Skolaris system.', { align: 'center' });
  }

  async generateCombinedReport(reportData, options = {}) {
    const doc = new PDFDocument({ ...this.defaultOptions, ...options });
    const buffers = [];

    return new Promise((resolve, reject) => {
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });
      doc.on('error', reject);

      this.generateCombinedReportContent(doc, reportData);
      doc.end();
    });
  }

  generateCombinedReportContent(doc, reportData) {
    const { student, semester, grades, attendance_summary, generated_at, average_grade, total_grades } = reportData;

    doc.fontSize(20).text('Complete Academic Report', { align: 'center' });
    doc.moveDown();

    doc.fontSize(14).text(`Student Name: ${student.nombre} ${student.apellido}`);
    doc.text(`Grade Level: ${student.grado}`);
    doc.text(`Email: ${student.email}`);
    doc.moveDown();

    doc.text(`Academic Period: ${semester.name} ${semester.year}`);
    doc.text(`Report Generated: ${moment(generated_at).format('MMMM DD, YYYY [at] h:mm A')}`);
    doc.moveDown();

    doc.fontSize(16).text('Academic Performance', { underline: true });
    doc.moveDown(0.5);

    if (grades && grades.length > 0) {
      this.drawGradesTable(doc, grades);
      doc.moveDown();
      doc.fontSize(14).text('Academic Summary', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12);
      doc.text(`Overall Average: ${average_grade}`);
      doc.text(`Total Subjects: ${total_grades}`);
    }

    doc.addPage();
    doc.fontSize(16).text('Attendance Summary', { underline: true });
    doc.moveDown(0.5);

    if (attendance_summary) {
      doc.fontSize(12);
      doc.text(`Total School Days: ${attendance_summary.total_days}`);
      doc.text(`Days Present: ${attendance_summary.days_present}`);
      doc.text(`Days Absent: ${attendance_summary.days_absent}`);
      doc.text(`Days Tardy: ${attendance_summary.days_tardy}`);
      doc.text(`Attendance Rate: ${attendance_summary.attendance_rate}%`);
    }

    doc.moveDown();
    doc.fontSize(10).text('This is an official combined academic report generated by the Skolaris system.', { align: 'center' });
  }

  savePDFToFile(pdfData, filename) {
    const filePath = path.join(__dirname, '../temp', filename);
    fs.writeFileSync(filePath, pdfData);
    return filePath;
  }
}

module.exports = new PDFGenerator();